# -*- mode: ruby -*-
# vi: set ft=ruby :

CONSULSERVER_COUNT = 3

Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.1"
  config.vm.provision "shell" , path: "install.sh", privileged:false

  CONSULSERVER_COUNT.times do |i|
    config.vm.define "consul-server#{i+1}" do |server|
      server.vm.network "private_network", ip: "192.168.0.#{i+1}"
      server.vm.hostname = "consul-server#{i+1}"
      server.vm.provider "virtualbox" do |vb|
       vb.memory = "2048"
       vb.cpus = 2
      end
	end
      
  end
end


