# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.1"

    config.vm.define "consul_server1" do |master|
      config.vm.network "private_network", ip: "192.168.0.1"
      master.vm.hostname = "consul_server1"
      master.vm.provider "virtualbox" do |vb|
       vb.memory = "2048"
       vb.cpus = 2
      end
    end

end