# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.1"
  #config.vm.provision "shell" , path: "install.sh", privileged:false

    config.vm.define "consul_portal" do |portal|
      portal.vm.network "public_network", ip: "192.168.0.77"
	  portal.vm.network :forwarded_port, guest: 8500, host: "8500"
      portal.vm.hostname = "consul_portal"
      portal.vm.provider "virtualbox" do |vb|
       vb.memory = "2048"
       vb.cpus = 2
      end
    end

end