# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.1"
  #config.vm.provision "shell" , path: "install.sh", privileged:false

    config.vm.define "consul-server2" do |master|
      config.vm.network "private_network", ip: "192.168.0.2"
      master.vm.hostname = "consul-server2"
      master.vm.provider "virtualbox" do |vb|
       vb.memory = "2048"
       vb.cpus = 2
      end
    end

end